with

final_data as (
select
    campaign_id,
    ssid,
    Lead_ID,
    clid,
    ad_id,
    fb_ad_name,
    fb_adset_id,
    fb_adset_name,
    fb_campaign_name,
    Original_Received,
    time_string,
    SID,
    id_number,
    blds_description,
    blds_mtn,
    blds_cellc,
    blds_blc,
    blds_mtn_BureauStatus,
    blds_mtn_BureauPass,
    Id_number_valid,
    mtn_sale,
    cellc_sale,
    ad_cost,
    ad_p_leads,
    ad_q_leads,
    ad_purchases,
    platform_costs,
    platform_p_leads,
    platform_q_leads,
    platform_purchases,
    campaign_costs,
    campaign_p_leads,
    campaign_q_leads,
    campaign_purchases
from {{ ref('leadbyte_costing_ad_id') }}
)

select
    campaign_id,
    ssid,
    Lead_ID,
    clid,
    ad_id,
    fb_ad_name,
    fb_adset_id,
    fb_adset_name,
    fb_campaign_name,
    Original_Received,
    time_string,
    SID,
    id_number,
    blds_description,
    blds_mtn,
    blds_cellc,
    blds_blc,
    blds_mtn_BureauStatus,
    blds_mtn_BureauPass,
    Id_number_valid,
sum(mtn_sale) as mtn_sale,
sum(cellc_sale) as cellc_sale,
sum(ad_cost) as cad_cost,
sum(ad_p_leads) as ad_p_leads,
sum(ad_q_leads) as ad_q_leads,
sum(ad_purchases) as ad_purchases,
sum(platform_costs) as platform_costs,
sum(platform_p_leads) as platform_p_leads,
sum(platform_q_leads) as platform_q_leads,
sum(platform_purchases) as platform_purchases,
sum(campaign_costs) as campaign_costs,
sum(campaign_p_leads) as campaign_p_leads,
sum(campaign_q_leads) as campaign_q_leads,
sum(campaign_purchases) as campaign_purchases,
sum(case when ad_id is null and campaign_id is null then platform_costs else (case when ad_id is null then campaign_costs else ad_cost end) end) as cost,
sum(case when ad_id is null and campaign_id is null then platform_p_leads else (case when ad_id is null then campaign_p_leads else ad_p_leads end) end) as p_leads,
sum(case when ad_id is null and campaign_id is null then platform_q_leads else (case when ad_id is null then campaign_q_leads else ad_q_leads end) end) q_leads,
sum(case when ad_id is null and campaign_id is null then platform_purchases else (case when ad_id is null then campaign_purchases else ad_purchases end) end) as p_purchases
from final_data
group by 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20